#!/bin/sh

export OSLAB_PATH=$(dirname `which $0`)

qemu-system-i386 -m 16M -boot a -drive file=$OSLAB_PATH/linux-0.11/Image,format=raw,if=floppy -drive file=$OSLAB_PATH/hdc-0.11.img,format=raw -s -S
