#!/bin/sh

export OSLAB_PATH=$(dirname `which $0`)

if [ ! -e "$OSLAB_PATH/hdc/umounted" ]; then
	echo umount hdc first
	sudo umount $OSLAB_PATH/hdc
	if [ "$?" != "0" ]; then
		exit
	fi
fi

bochs -q -f $OSLAB_PATH/bochs/linux-0.11-gui.bxrc	
